Writing a function

In [1]:
def is_leap(year):
    leap = False
        
    if year % 400 == 0 or (year % 4 == 0 and year % 100 != 0):

        leap = True
    else:
        leap = False
        
    return leap

Printing a function

In [2]:
if __name__ == '__main__':
    n = int(input())
    for i in range (1,n+1):
        print(i, end='')

4
1234

What's your name?

In [3]:
def print_full_name(a, b):
    print("Hello {} {}! You just delved into python.".format(a,b))

String Formatting

In [5]:
def print_formatted(num):
    w=len(str(bin(num))[2:])
    for number in range(1,num+1):
        print((str(number)).rjust(w)+(str(oct(number))[2:]).rjust(w+1)+((str(hex(number)).upper())[2:]).rjust(w+1)+(str(bin(number))[2:]).rjust(w+1))

Introduction to Sets

In [6]:
def average(array):
    # your code goes here
    k = set(array)
    #return k.sum()/k.len()
    return sum(k)/len(k)

Symmetric Difference

In [8]:
m = int(input())
mset = set(map(int, input().split()))
n = int(input())
nset = set(map(int, input().split()))
diff = sorted(mset.difference(nset) | nset.difference(mset))
#diff = sorted(mset ^ nset)
for i in diff:
    print(i)


4
2 4 5 9
4
2 4 11 2
5
9
11


Set.add()

In [9]:
print(len(set([str(input()) for x in range(int(input()))])))

4
5
2
4

4


Set.union() Operation

In [10]:
print(len((set(input().split()) if input() != '-1' else '')|(set(input().split()) if input() != '-1' else '')))

9
1
2
3
2


Arrays using NumPy

In [12]:
def arrays(arr):
    arr = numpy.array(arr,float)
    return (arr[::-1])

Shape and Reshape

In [13]:
import numpy
print(numpy.reshape(numpy.array(input().split(),int),(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
