Transpose and Flatten

In [1]:
import numpy
n,m = map(int,input().split())
mat = numpy.array([input().split() for i in range(n)],int)

print(mat.transpose())
print(mat.flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


Concatenate

In [2]:
import numpy as np
n,m,p = map(int,input().split())
a = np.array([input().split() for _ in range(n)],int)
b = np.array([input().split() for _ in range(m)],int)

print(np.concatenate((a,b), axis=0))

4 3 2
1 2 
1 2 
1 2 
3 4
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]
 [3 4]]


Zeros and Ones

In [3]:
import numpy as np
size = tuple(map(int,input().split()))
print(np.zeros(size, dtype = np.int))
print(np.ones(size, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Eye and Identity

In [4]:
import numpy
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Array Mathematics

In [5]:
import numpy as np
n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4 
4 5 6 7
[[ 5  7  9 11]]
[[-3 -3 -3 -3]]
[[ 4 10 18 28]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    32   729 16384]]


Floor, Ceil and Rint

In [6]:
import numpy

numpy.set_printoptions(sign=' ')

a = numpy.array(input().split(),float)

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


Sum and Prod

In [7]:
import numpy as np
n,m = map(int,input().split())
array = np.array([input().split() for _ in range(n)],int)
print(np.prod(np.sum(array, axis=0), axis=0))

2 2
1 2
3 4
24


Min and Max

In [8]:
import numpy as np
N, M = map(int, input().split())
A = np.array([input().split() for _ in range(N)],int)
print(np.max(np.min(A, axis=1), axis=0))

4 2
2 5
3 7
1 3
4 0
3


Mean, Var and Std

In [9]:
import numpy as np

N, M = map(int, input().split())
array = np.array([input().split() for _ in range(N)],int)
np.set_printoptions(legacy='1.13')
print(np.mean(array, axis=1))
print(np.var(array, axis=0))
print(np.std(array, axis=None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


Dot and Cross

In [10]:
import numpy as np
n = int(input())
a = np.array([input().split() for _ in range(n)],int)
b = np.array([input().split() for _ in range(n)],int)
print(np.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]
